spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: core-service-dev
    password: core-service-dev
